version: '2'
services:
  mongodb:
    image: "mongo:3"
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://172.19.0.4:9000/api
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
  rabbitmq:
      image: "rabbitmq:3.6.10-management"
      environment:
        RABBITMQ_ERLANG_COOKIE: "symtest"
