version: "2"
services:
    php:
        build: ./build/php
        volumes: 
            - ../:/var/www/testapp
        depends_on:
            - rabbitmq
        networks:
            testapp_net:
                ipv4_address: 172.20.0.2
    nginx:
        build: ./build/nginx
        depends_on:
            - php
        networks:
            testapp_net:
                ipv4_address: 172.20.0.3
    rabbitmq:
        image: "rabbitmq:3.6.10-management"
        environment:
            RABBITMQ_ERLANG_COOKIE: "testapp"
        networks:
            testapp_net:
                ipv4_address: 172.20.0.4
    elasticsearch:
        image: "elasticsearch:2"
        command: "elasticsearch -Des.cluster.name='graylog'"
        networks:
            testapp_net:
                ipv4_address: 172.20.0.5
    mongodb:
        image: "mongo:3"
        networks:
            testapp_net:
                ipv4_address: 172.20.0.6
    graylog:
        image: graylog2/server:2.1.1-1
        environment:
            GRAYLOG_PASSWORD_SECRET: somepasswordpepper
            GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            GRAYLOG_WEB_ENDPOINT_URI: http://172.20.0.7:9000/api
        links:
            - mongodb:mongo
            - elasticsearch:elasticsearch
        networks:
            testapp_net:
                ipv4_address: 172.20.0.7
networks:
    testapp_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1